name: GUI Workflow

on:
  push:
    branches: [main]
    paths:
      - 'gui/**'
  pull_request:
    paths:
      - 'gui/**'

env:
  EXECUTABLES: "zappy_gui"

jobs:
  check_compilation:
    name: Check GUI compilation
    runs-on: ubuntu-latest
    container: 
      image: epitechcontent/epitest-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Change directory to gui
        run: cd gui

      - name: Build GUI
        run: |
          cmake -B .build
          cmake --build .build
